# image:   bcbdockerdevreg.mdanderson.edu:5443/jma7/vtools_hdf5:test

stages:
        #        - build 
        - test
#stages:
##        - setup
##        - test       
##services:
##        - vtools_hdf5:latest 
#        #        - bcbdockerdevreg.mdanderson.edu:5443/jma7/vtools_hdf5:test
#        #setup:
#        #        stage: setup
#        #        script:
#        #                - cd ~/Development/VAT/VariantTools/
#        #                - python setup.py install 
#        #                - cd test
#
#        #before_script:
#        #        -
#


#build:
#        stage: build
before_script:

                # - git checkout v3
                # - git pull
                # - cp -r /home/bpeng/VariantTools/boost_1_49_0 /home/jma7/VariantTools/src
                # - cp -r /home/bpeng/VariantTools/cgatools /home/jma7/VariantTools/src
                # - cp -r /home/bpeng/VariantTools/gsl /home/jma7/VariantTools/src
                # - cp -r /home/bpeng/VariantTools/libplinkio /home/jma7/VariantTools/src
                # - cp -r /home/bpeng/VariantTools/rext /home/jma7/VariantTools/src
                # - cp -r /home/bpeng/VariantTools/sqlite /home/jma7/VariantTools/src
                # - cp -r /home/bpeng/VariantTools/ucsc /home/jma7/VariantTools/src
                # - cp -r /home/bpeng/.variant_tools /home/jma7/.variant_tools
                # - python setup.py install
                - cd test
test_admin:
        stage: test
        script:
                - python test_admin.py

test_associate:
        stage: test
        script:
                - python test_associate.py

# test_avg_depth:
#         stage: test
#         script:
#                 - python test_avg_depth.py

# test_compare:
#         stage: test
#         script:
#                 - python test_compare.py


