image:   bcbdockerdevreg.mdanderson.edu:5443/jma7/vtools_hdf5:test
stages:
        #        - build 
        - test
#stages:
##        - setup
##        - test       
##services:
##        - vtools_hdf5:latest 
#        #        - bcbdockerdevreg.mdanderson.edu:5443/jma7/vtools_hdf5:test
#        #setup:
#        #        stage: setup
#        #        script:
#        #                - cd ~/Development/VAT/VariantTools/
#        #                - python setup.py install 
#        #                - cd test
#
#        #before_script:
#        #        -
#


#build:
#        stage: build
before_script:

                - git checkout v3
                - git pull
                - cp -r /home/bpeng/VariantTools/boost_1_49_0 ./src
                - cp -r /home/bpeng/VariantTools/cgatools ./src
                - cp -r /home/bpeng/VariantTools/gsl ./src
                - cp -r /home/bpeng/VariantTools/libplinkio ./src
                - cp -r /home/bpeng/VariantTools/rext ./src
                - cp -r /home/bpeng/VariantTools/sqlite ./src
                - cp -r /home/bpeng/VariantTools/ucsc ./src
                - cp -r /home/bpeng/.variant_tools .
                - python setup.py install
                - cd test
test_admin:
        stage: test
        script:
                - python test_admin.py

test_associate:
        stage: test
        script:
                - python test_associate.py

# test_avg_depth:
#         stage: test
#         script:
#                 - python test_avg_depth.py

# test_compare:
#         stage: test
#         script:
#                 - python test_compare.py


