image: gitlab/gitlab-runner:latest

#before_script:
#       - sudo apt-get install swig zlibc zlib1g zlib1g-dev libblas-dev liblapack-dev
#       - python setup.py install 
#       - cd test

testScript:
        script:
          - python test_init.py
   
