image:   bcbdockerdevreg.mdanderson.edu:5443/jma7/vtools_hdf5:test

stages:
        - build 
        - test
#stages:
##        - setup
##        - test       
##services:
##        - vtools_hdf5:latest 
#        #        - bcbdockerdevreg.mdanderson.edu:5443/jma7/vtools_hdf5:test
#        #setup:
#        #        stage: setup
#        #        script:
#        #                - cd ~/Development/VAT/VariantTools/
#        #                - python setup.py install 
#        #                - cd test
#
#        #before_script:
#        #        -
#


build:
        stage: build
        script:
                #  - git checkout v3
                #  - git pull
                 - cd /home/jma7/VariantTools
                 - python setup.py install

test_admin:
        stage: test
        script:
                - cd test
                - python test_admin.py

test_associate:
        stage: test
        script:
                - python test_associate.py

test_avg_depth:
        stage: test
        script:
                - python test_avg_depth.py

test_compare:
        stage: test
        script:
                - python test_compare.py

test_exclude:
        stage: test
        script:
                - python test_exclude.py

test_execute:
        stage: test
        script:
                - python test_execute.py

