#image: gitlab/gitlab-runner:latest

stages:
        - setup
        - test       
#services: 
#        - bcbdockerdevreg.mdanderson.edu:5443/jma7/vtools_hdf5:test
setup:
        stage: setup
        script:
                - cd ~/Development/VAT/VariantTools/
                - python setup.py install 
                - cd test

test:
        script:
          - python test_init.py
   
