image:   bcbdockerdevreg.mdanderson.edu:5443/jma7/vtools_hdf5_ci:test
stages:
        #        - build 
        - test
#stages:
##        - setup
##        - test       
##services:
##        - vtools_hdf5:latest 
#        #        - bcbdockerdevreg.mdanderson.edu:5443/jma7/vtools_hdf5:test
#        #setup:
#        #        stage: setup
#        #        script:
#        #                - cd ~/Development/VAT/VariantTools/
#        #                - python setup.py install 
#        #                - cd test
#
#        #before_script:
#        #        -
#


#build:
#        stage: build
before_script:

                - git checkout v3
                - git pull
                - cp -r /home/bpeng/VariantTools/src/boost_1_49_0 ./src
                - cp -r /home/bpeng/VariantTools/src/cgatools ./src
                - cp -r /home/bpeng/VariantTools/src/gsl ./src
                - cp -r /home/bpeng/VariantTools/src/libplinkio ./src
                - cp -r /home/bpeng/VariantTools/src/rext ./src
                - cp -r /home/bpeng/VariantTools/src/sqlite ./src
                - cp -r /home/bpeng/VariantTools/src/ucsc ./src
                - cp -r /home/bpeng/.variant_tools ../
                # - cp -r /home/bpeng/VariantTools/build .
                - python setup.py install
                - cd test
test_admin:
        stage: test
        script:
                - python test_admin.py

test_associate:
        stage: test
        script:
                - python test_associate.py

test_avg_depth:
        stage: test
        script:
                - python test_avg_depth.py

test_compare:
        stage: test
        script:
                - python test_compare.py

test_exclude:
        stage: test
        script:
                - python test_exclude.py

test_execute:
        stage: test
        script:
                - python test_execute.py

test_export:
        stage: test
        script:
                - python test_export.py

test_func:
        stage: test
        script:
                - python test_func.py

test_import:
        stage: test
        script:
                - python test_import.py

test_init:
        stage: test
        script:
                - python test_init.py

test_liftover:
        stage: test
        script:
                - python test_liftover.py

test_output:
        stage: test
        script:
                - python test_output.py

test_phenotype:
        stage: test
        script:
                - python test_phenotype.py

test_remove:
        stage: test
        script:
                - python test_remove.py

test_select:
        stage: test
        script:
                - python test_select.py

test_show:
        stage: test
        script:
                - python test_show.py

test_trans_ratio:
        stage: test
        script:
                - python test_trans_ratio.py

test_update:
        stage: test
        script:
                - python test_update.py

test_use:
        stage: test
        script:
                - python test_use.py




