image:   bcbdockerdevreg.mdanderson.edu:5443/jma7/vtools_hdf5_ci:test
stages:
        #        - build 
        - testSqlite
        - testHDF5
#stages:
##        - setup
##        - test       
##services:
##        - vtools_hdf5:latest 
#        #        - bcbdockerdevreg.mdanderson.edu:5443/jma7/vtools_hdf5:test
#        #setup:
#        #        stage: setup
#        #        script:
#        #                - cd ~/Development/VAT/VariantTools/
#        #                - python setup.py install 
#        #                - cd test
#
#        #before_script:
#        #        -
#

#build:
#        stage: build

# variables:
#         storeMode: "hdf5"


before_script:

                - git checkout v3
                - git pull
                - cp -r /home/bpeng/VariantTools/src/boost_1_49_0 ./src
                - cp -r /home/bpeng/VariantTools/src/cgatools ./src
                - cp -r /home/bpeng/VariantTools/src/gsl ./src
                - cp -r /home/bpeng/VariantTools/src/libplinkio ./src
                - cp -r /home/bpeng/VariantTools/src/rext ./src
                - cp -r /home/bpeng/VariantTools/src/sqlite ./src
                - cp -r /home/bpeng/VariantTools/src/ucsc ./src
                # - cp -r /home/bpeng/.variant_tools ../
                # - cp -r /home/bpeng/VariantTools/build .
                - python setup.py install
                - cd test

# test_admin-associate-avg_depth-compare:
#         stage: testSqlite
#         variables:
#                 STOREMODE: "sqlite"
#         script:
#                 - python test_admin.py
#                 - python test_associate.py
#                 - python test_avg_depth.py
#                 - python test_compare.py

test_show-trans_ratio-update-use:
        stage: testSqlite
        variables:
                STOREMODE: "sqlite"
        script:
                # - python test_show.py
                - python test_trans_ratio.py
                # - python test_update.py
                # - python test_use.py

# test_exclude-execute-export:
#         stage: testSqlite
#         variables:
#                 STOREMODE: "sqlite"
#         script:
#                 - python test_exclude.py
#                 - python test_execute.py
#                 - python test_export.py

# test_output-phenotype-remove-select:
#         stage: testSqlite
#         variables:
#                 STOREMODE: "sqlite"
#         script:
#                 - python test_output.py
#                 - python test_phenotype.py
#                 - python test_remove.py
#                 - python test_select.py

# test_import:
#         stage: testSqlite
#         varialble:
#                 STOREMODE: "sqlite"
#         script:
#                 - python test_import.py

# test_init-listover-func:
#         stage: testSqlite
#         variables:
#                 STOREMODE: "sqlite"
#         script:
#                 - python test_init.py
#                 - python test_liftover.py
#                 - python test_func.py


test_admin-compare-execute:
        stage: testSqlite
        variables:
                STOREMODE: "hdf5"
        script:
                - python test_init.py
                - python test_liftover.py
                - python test_func.py


# test_liftover-use-select:
#         stage: testHDF5
#         variables:
#                 STOREMODE: "hdf5"
#         script:
#                 - python test_init.py
#                 - python test_liftover.py
#                 - python test_func.py

# test_output-phenotype-remove:
#         stage: testHDF5
#         variables:
#                 STOREMODE: "hdf5"
#         script:
#                 - python test_output.py
#                 - python test_phenotype.py
#                 - python test_remove.py
#                 - python test_select.p


# test_associate:
#         stage: test
#         script:
#                 - python test_associate.py

# test_avg_depth:
#         stage: test
#         script:
#                 - python test_avg_depth.py

# test_compare:
#         stage: test
#         script:
#                 - python test_compare.py



# test_execute:
#         stage: test
#         script:
#                 - python test_execute.py

# test_export:
#         stage: test
#         script:
#                 - python test_export.py

# test_func:
#         stage: test
#         script:
#                 - python test_func.py



# test_liftover:
#         stage: test
#         script:
#                 - python test_liftover.py



# test_phenotype:
#         stage: test
#         script:
#                 - python test_phenotype.py

# test_remove:
#         stage: test
#         script:
#                 - python test_remove.py

# test_select:
#         stage: test
#         script:
#                 - python test_select.py



# test_trans_ratio:
#         stage: test
#         script:
#                 - python test_trans_ratio.py

# test_update:
#         stage: test
#         script:
#                 - python test_update.py

# test_use:
#         stage: test
#         script:
#                 - python test_use.py




